### ISSUE TITLE
If HorizonDialogueMsgTextBlock doesn't have 'Size to Content' it doesn't wraps properly

### ISSUE THREAD

**Issue by lotsofbugs** [dorgonman/HorizonUIPluginDemo#8]
Due to my widget hierarchy and design, my HorizonDialogueMsgTextBlock doesn't contains a Size to Content property, so I can't set it to true. Without this, my MsgTextBlocks stays broken.

![image](https://user-images.githubusercontent.com/23303304/140522478-1b89a36c-41e0-4996-9a69-cce4fa533efd.png)

This is my hierarchy right now. I'm using 4.27

**Comment by dorgonman** [comment]
hi, maybe you can try to adjust SizeBox's Width and Height override?

![image](https://user-images.githubusercontent.com/1768035/140529182-48643fca-3387-46b7-a144-1c4e84664009.png)

**Comment by dorgonman** [comment]
Hi, I can't recreate your issue, could you please check your plugin version is 4.27.0 in Edit->Plugin page:

![image](https://user-images.githubusercontent.com/1768035/140542632-509b5455-4906-432d-b067-00e18ec4f473.png)

Or could you please recreate the issue with an empty project and send it to me, so I can take a look?

**Comment by lotsofbugs** [comment]
[UI_Dialogue.zip](https://github.com/dorgonman/HorizonUIPluginDemo/files/7487486/UI_Dialogue.zip)

Uploaded only the widget uasset.
And yes, I'm using 4.27 version. Thanks for your attention in advance

**Comment by dorgonman** [comment]
hi, Just take a look into the issue, I think i will need add some code and flag to handle this issue. 

The fix is planned with next engine release.

As quick fix, you can change SizeBox's parent into  CanvasPanel ad set SizeX and SizeY in slot

![image](https://user-images.githubusercontent.com/1768035/140549409-77fdcb1c-4ce7-4b97-9d64-335ee87904eb.png)

Or you can change RootWidget to Overlay and use Padding and Alignment to adjust your widget's position

![image](https://user-images.githubusercontent.com/1768035/140549863-10ca9e57-341c-4582-a470-0b8bb6427edb.png)

Thanks

**Comment by lotsofbugs** [comment]
Thanks @dorgonman ! Solved!
